import * as yup from 'yup';

export const truckFormSchema = yup.object({
  listingTitle: yup.string().required('Listing Title is required'),
  make: yup.string().required('Make is required'), 
  model: yup.string().required('Model is required'),
  condition: yup.string().required('Condition is required'),
  inventoryLocation: yup.string().required('Inventory Location is required'),
  transmission: yup.string().required('Transmission is required'),
  fuelType: yup.string().required('Fuel Type is required'),
  axleConfig: yup.string().required('Axle Configuration is required'),
  category: yup.string().required('Category is required'), 
  hotLocation: yup.string().required('Hot Location is required'),
  steering: yup.string().required('Steering is required'),
  color: yup.string().required('Color is required'),
  engineSize: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Engine Size is required'),
  year: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Year is required'),
  price: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Price is required'),
  doors: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Number of Doors is required'),
  seats: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Number of Seats is required'),
  modelCode: yup.string().required('Model Code is required'),
  auctionGrade: yup.string().required('Auction Grade is required'),
  loadingCapacity: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Loading Capacity is required'),
  mileage: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Mileage is required'),
  engineNumber: yup.string().required('Engine Number is required'),
  chassisNo: yup.string().required('Chassis No is required'),
  dimensionLength: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Length is required'),
  dimensionWidth: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Width is required'),
  dimensionHeight: yup.number().nullable().transform((value) => (isNaN(value) ? 0 : value)).required('Height is required'),
  carOptions: yup.array().default([]).required('Car options are required'),
  vin: yup.string().default(''),
  stockNumber: yup.string().default(''),
  imageBase64: yup.string().default(''),
  description: yup.string().default(''),
  dealerStock: yup.boolean().default(false)
});
